# Generated by Django 3.1.4 on 2021-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(max_length=50)),
                ('date_of_issue', models.DateField(max_length=50)),
                ('date_of_expiry', models.DateField(max_length=100)),
            ],
        ),
    ]
