# Generated by Django 3.1.4 on 2021-02-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kyc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
