# Generated by Django 3.1.4 on 2021-02-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_delete_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.BooleanField(default=False)),
                ('voter_card', models.BooleanField(default=False)),
                ('passport', models.BooleanField(default=False)),
                ('driving_license', models.BooleanField(default=False)),
                ('passbook', models.BooleanField(default=False)),
                ('bank_statement', models.BooleanField(default=False)),
                ('pan', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
